language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
  yarn: true
install:
  - yarn install
  - yarn global add @formatjs/cli
script:
  - yarn test
branches:
  only:
    - master
    - staging