language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
  yarn: true
install:
  - yarn install
script:
  - yarn build
branches:
  only:
    - master
    - staging
notifications:
  webhooks:
    urls:
      - https://neowise.feuerschutz.ch/webhook/travis
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
